# Generated by Django 5.1.1 on 2024-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_recipe_ingredients_list_recipe_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients_list",
            field=models.TextField(default=0),
        ),
    ]
