# Generated by Django 5.1.1 on 2024-09-26 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_recipe_ingredients_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients_list",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="steps_list",
        ),
    ]
